name: Deploy Docs to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
